version: '3.1'

services:
  db:
    image: mysql:5.7
    restart: always
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: api
    ports:
      - 3307:3306
    volumes:
      - db-data:/var/lib/mysql

  testdb:
    image: mysql:5.7
    restart: always
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: apitest
    ports:
      - 3308:3306
    volumes:
      - db-data2:/var/lib/mysql

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

volumes:
  db-data:
  db-data2: